# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YaqZ3N9jT26US6q0A70qs2_RvmmBDBbi
"""

import pandas as pd

productos = {
    "Producto": ["Arroz 2kg", "Aceite 1L", "Leche 1L", "Café 400g"],
    "Precio_anterior": [3.20, 2.75, 1.05, 4.80],
    "Precio_actual": [5.00, 2.69, 1.12, 5.25]
}

df = pd.DataFrame(productos)
df["Variacion_%"] = (
    (df["Precio_actual"] - df["Precio_anterior"])
    / df["Precio_anterior"] * 100
).round(2)
df["Alerta"] = df["Variacion_%"].apply(
    lambda x: "SUBIÓ" if x > 5 else ("BAJÓ" if x < 0 else "ESTABLE")
)

print("MONITOR INTELIGENTE DE PRECIOS")
print("=" * 50)
print(df.to_string(index=False))